export const CodeErrorMessage = {
  TIMEOUT: 'Tempo Excedido',
  UNKNOWN_ERROR: 'Erro Desconhecimento',
  UNAUTHORIZED: 'Não Autorizado',
  ACCESS_DENIED: 'Acesso Negado',
  INTERNAL_SERVER_ERROR: 'Erro interno no servidor',
  NETWORK_ERROR: 'Erro de comunicação, certifique-se sua conexão com a internet',
  FAILED_FIRST_ACCESS: 'Falha ao realizar o primeiro acesso',
  FAILED_CHANGE_PASSWORD: 'Falha ao alterar senha',
  FAILED_REQUEST_CHANGE_PASSWORD: 'Falha ao solicitar recuperação de senha',
  FAILED_LOAD_DASHBOARD: 'Falha ao carregar dashboard',
  FAILED_LOAD_ANIMAL: 'Falha ao carregar animal',
  FAILED_LOAD_VACCINE: 'Falha ao carregar vacina',
  FAILED_LOAD_PERSON: 'Falha ao carregar pessoa',
  FAILED_CREATE_PERSON: 'Falha ao criar pessoa',
  FAILED_CHANGE_PERSON: 'Falha ao atualizar pessoa',
  FAILED_LOAD_USER: 'Falha ao carregar usuário',
  FAILED_CREATE_USER: 'Falha ao criar usuário',
  FAILED_ENABLE_USER: 'Falha ao ativar usuário',
  FAILED_DISABLE_USER: 'Falha ao desativar usuário',
};
